# Generated by Django 6.0.3 on 2026-03-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('caregiver', models.ForeignKey(blank=True, limit_choices_to={'role': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_caregiver', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_as_parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
